name: Deploy Laravel App to SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # or your Laravel PHP version
          extensions: mbstring, bcmath, xml, json, mysql # any required PHP extensions

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Laravel cache and assets
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan migrate --force  # Run migrations
        env:
          APP_ENV: production
          APP_KEY: ${{ secrets.APP_KEY }}
          DB_CONNECTION: mysql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Deploy to SiteGround via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add the SSH host (with port) to known hosts to avoid interactive prompt
          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts

          # Use rsync to deploy the code
          rsync -avz --delete \
          --exclude='storage/' \
          --exclude='.env' \
          --exclude='.git/' \
          --exclude='vendor/' \
          -e "ssh -p $SSH_PORT" \
          ./ $SSH_USER@$SSH_HOST:/www/gladlio.com/public_html
